### ISSUE TITLE
Vulnerable Dependency Hoek

### ISSUE THREAD

**Issue by maxwell-bland** [ucsdcses/blueprintcs-live#1]
Seems like Hoek is outdated, can we look into this? I'll do it tonight if possible.

**Comment by jsdavis** [comment]
Hoek? Which package depends on it?

**Comment by jsdavis** [comment]
Wait found it. Didn't know GitHub had that feature, neat

**Comment by jsdavis** [comment]
Answer is a solid maybe. This event is in 11 days, and this site won't be hosted on our server, won't have any sensitive information, and will only need to work for about 12 hours or so. Therefore, development speed is much higher priority than security right now, and even the potential threat is an inconvenience at worst. I'll still take a look though

**Comment by jsdavis** [comment]
So looks like it's an old dependency that's a few levels deep in `node-sass`'s dependency tree. Since `node-sass` is only a development dependency, and has no risk of being used in production, and further given the circumstances under which this site will be operating, I'm considering this to be an acceptable security flaw, and am closing the issue
